---
- name: Create komga user
  ansible.builtin.user:
    name: "{{ komga_container_user }}"
    shell: /sbin/nologin
    create_home: true
    state: present
  become: true

- name: get created user metadata
  ansible.builtin.getent:
    database: passwd
    key: "{{ komga_container_user }}"

- name: Setting user id and group id facts
  ansible.builtin.set_fact:
    created_uid: "{{ ansible_facts.getent_passwd[komga_container_user].1 }}"
    created_gid: "{{ ansible_facts.getent_passwd[komga_container_user].2 }}"

- name: Ensure komga folders exists
  become: true
  ansible.builtin.file:
    dest: "{{ item }}"
    owner: "{{ komga_container_user }}"
    group: "{{ komga_container_user }}"
    state: directory
    mode: 0755
  loop:
    - "{{ komga_host_config_path }}"
    - "{{ komga_host_data_path }}"

- name: Copy komga docker-compose template.
  ansible.builtin.template:
    src: templates/docker-compose.yml.j2
    dest: "{{ komga_host_config_path }}/docker-compose.yml"
    owner: "{{ komga_container_user }}"
    group: "{{ komga_container_user }}"
    mode: 0644
  become: true

- name: Create systemd komga service.
  ansible.builtin.template:
    src: templates/komga.service.j2
    dest: "/etc/systemd/system/komga.service"
    mode: 0644
  become: true

- name: Ensure komga.service is started
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: komga
  become: true

- name: Check komga container
  ansible.builtin.uri:
    url: "http://localhost:{{ komga_host_port }}"
  register: result
  until: result.status == 200
  retries: 5
  delay: 30

- name: Remove old image versions
  become: true
  community.docker.docker_prune:
    images: true
    images_filters:
      dangling: false
  notify: Restart Docker service
